repository: takumin/boilerplate-golang-cli
summary:
  if: true
comment:
  if: is_pull_request
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
coverage:
  paths:
  - coverage.out
codeToTestRatio:
  code:
  - '**/*.go'
  - '!**/*_test.go'
  test:
  - '**/*_test.go'
testExecutionTime:
  acceptable: 3min
